frontend init-containers: Includes init containers to pod containers
headlamp-k8s/headlamp pull request #1007
Opened 2023-03-13 17:05 UTC by vyncent-t

For issue #983 

Creates an additional field for Init containers under the regular containers when in the pod view.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/78232183/224773810-dcc3e24a-fc63-4589-b533-e0a006664ded.png">

2023-03-13 19:18 UTC, joaquimrocha requested changes
Left some comments in the code.
Also, the commit title shouldn't have `init containers` in the prefix, just frontend is enough.

If you want to reuse the exact same code, you could also pass an "isInit" property to the `ContainersSection`, and then add a second `<ContainerSection isInit={true}...`.

2023-03-13 19:18 UTC, joaquimrocha commented on frontend/src/components/common/Resource/Resource.tsx
> +    return initContainers;
I think this can be simplified with `return resource?.spec?.initContainers || [];`

2023-03-13 19:18 UTC, joaquimrocha commented on frontend/src/components/common/Resource/Resource.tsx
> +          <SectionBox title={t(`resource| Init Containers`)} />
The namespace separator (`|`) shouldn't have spaces around it.

2023-03-13 19:18 UTC, joaquimrocha commented on frontend/src/components/common/Resource/Resource.tsx
> +            <SectionBox key={i} outterBoxProps={{ pt: 1 }}>
I know you just used what's written for the regular containers, but the `key` should be textual, so `key={`init_container_${i}`}` is better; and `initContainer` should have the proper type (`KubeContainer` I think).

2023-03-13 19:18 UTC, joaquimrocha commented on frontend/src/components/common/Resource/Resource.tsx
> +            <SectionBox key={i} outterBoxProps={{ pt: 1 }}>
Feel free to also modify the regular container's key+type in a different commit if you want.

2023-03-13 19:55 UTC, vyncent-t commented
[x] updated the build snapshots
[x] commit title edit
[x] simplified with return resource?.spec?.initContainers || []
[x] namespace separator (|) shouldn't have spaces around it
[x] contextual edits

- left the original context container as is, will change with another commit as mentioned

2023-03-14 15:32 UTC, joaquimrocha requested changes

2023-03-14 15:32 UTC, joaquimrocha commented on frontend/src/components/common/Resource/Resource.tsx
> +        </SectionBox>
We should not display anything if there are no initContainers.

2023-03-14 15:32 UTC, joaquimrocha commented on frontend/src/components/common/Resource/Resource.tsx
> +          <SectionBox title={t(`resource|Init Containers`)} />
Please use single quotes here.

2023-03-15 21:01 UTC, joaquimrocha approved these changes

2023-03-15 21:01 UTC, merged