WIP: frontend: k8s: Adding docs, improving types
headlamp-k8s/headlamp pull request #1327
Opened 2023-08-15 17:24 UTC by illume

2023-09-14 14:03 UTC, joaquimrocha requested changes
Left a few comments. Some are nits/suggestions, some are about typos and logic that needs to be fixed.
Thank you for such a big review of these modules and the changes!

2023-09-14 14:03 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
This was quite a lot of work. Thanks for that.
I see that many fields to have the same description as in their official docs, so I wonder if it would have been faster to just add the link to them, but I am not sure of what the criteria should be for documenting some and not others, given I agree that it's useful to have some examples/extra-info directly documented in these.

2023-09-26 06:32 UTC, illume commented on frontend/src/lib/k8s/cluster.ts
Having documentation there is quite handy when modifying this code, or code that uses these structures. Just having a link would be cumbersome imho.

2023-09-26 06:33 UTC, illume commented
I addressed the notes by @joaquimrocha  (thanks!).

2023-09-29 12:50 UTC, illume commented
Fixed a conflict.

2023-10-05 14:39 UTC, illume commented
rebased against main

2023-10-11 09:53 UTC, joaquimrocha commented on frontend/src/helpers/index.ts
> + * setRecentCluster adds the cluster name to the list of recent clusters in localStorage.
Remove function name.

2023-10-11 09:53 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +   */
Seems odd to have a field not added here but documented.

2023-10-11 11:14 UTC, illume commented on frontend/src/lib/k8s/apiProxy.ts
> +      return data as DrainNodeStatus;
Cool, that looks nice (and works).

2023-10-11 11:26 UTC, joaquimrocha requested changes
Found some more function names repeated in the respective docs.

2023-10-11 11:26 UTC, joaquimrocha commented on frontend/src/lib/k8s/apiProxy.ts
> + * asQuery converts the given query parameters to a URL query string.
Remove function name.

2023-10-11 11:26 UTC, joaquimrocha commented on frontend/src/lib/k8s/apiProxy.ts
> + * refreshToken checks if the token is about to expire and refreshes it if so.
Remove function name.

2023-10-11 11:26 UTC, joaquimrocha commented on frontend/src/lib/k8s/apiProxy.ts
> + * getClusterAuthType returns the auth type of the cluster.
Remove function name.

2023-10-11 11:26 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> + * makeKubeObject creates a KubeObject implementation for the given object name.
Remove function name.

2023-10-11 11:51 UTC, illume commented on frontend/src/lib/k8s/cluster.ts
> +   */
I removed the comment, and just left the todo there for a future pass.

2023-10-11 12:27 UTC, illume commented
Thanks @joaquimrocha 

(I've addressed all the notes.)

2023-10-11 13:37 UTC, illume commented
That rebase oopsie should be fixed now.

2023-10-11 13:41 UTC, joaquimrocha approved these changes

2023-10-11 14:55 UTC, merged