frontend: test for repeat translate keys
headlamp-k8s/headlamp pull request #1330
Opened 2023-08-16 20:40 UTC by vyncent-t

# Testing for Duplicated Keys in Translation Files

fixes #1300
fixes #1426 

#### **Background**:
With our current approach to i18n, using namespaced translations could lead us into accidentally duplicating translation strings. This might increase the translation work unnecessarily.

#### **Solution**:
- Implement a testing mechanism to ensure we don't have duplicated keys across different translation files.
- Develop a way to whitelist specific keys that can be intentionally duplicated, taking into account language nuances.

#### **Changes**:
- [x] Introduced a test script that detects duplicated keys in all translation files.
- [x] Created a whitelist file where allowable duplicated keys can be defined.

#### **Next Steps**:
- Enhance the detection mechanism for more nuanced cases.
- Discuss and finalize keys that might need whitelisting due to language intricacies.

2023-08-17 16:11 UTC, vyncent-t commented
WIP - console logs the "original" key and its value and the duplicates
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/41c15863-cd37-4776-b4b1-eb771b7ff36d)

2023-08-17 20:35 UTC, vyncent-t commented
I wonder if for the mechanism we can utilize the context field for languages that may reuse words?
https://www.i18next.com/translation-function/context

2023-08-18 16:32 UTC, vyncent-t commented
WIP
Current commit now includes a way to whitelist words by manually inputting them into the whitelist.json file.

example:
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/b38c3b68-4da3-4650-9adc-6b68d58b1a5d)

when running test:
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/0ef8168d-e1af-468c-ab64-7fe0d7f03331)

2023-08-18 16:57 UTC, vyncent-t commented
Commit note:
- removed example whitelist word
- added counter for test

2023-09-08 13:50 UTC, illume requested changes
Cool.

I added a few notes. Did you see there is a test failure?

2023-09-08 13:50 UTC, illume commented on frontend/src/i18n/locales/keys.test.ts
> +const whitelist = require('./whitelist.json');
Can you please change this to allowlist?

2023-09-08 13:50 UTC, illume commented on frontend/src/i18n/locales/keys.test.ts
> +import { error } from 'console';
I feel there should be a description of this test that's a bit more 
- near the top
- descriptive when it fails. Currently the test is called "Translation keys", but it should give people a clue what is happening and what they need to do right away when it fails in the error message given in the failure. `npm run test` should describe the problem and what to do to fix it.

2023-09-12 17:33 UTC, joaquimrocha requested changes
Left a couple of comments, mostly on readability.

2023-09-12 17:33 UTC, joaquimrocha commented on frontend/src/i18n/locales/keys.test.ts
> +    }
Nit: Usually, for readability, we check for the inexistence of what we need, and initialize it before proceeding with the regular logic.
```typescript
    if (!wordMap[lang]) {
      wordMap[lang] = [contents[i]];      
    }

    wordMap[lang].push(contents[i]);
```

2023-09-12 17:33 UTC, joaquimrocha commented on frontend/src/i18n/locales/keys.test.ts
> +    const fileName = filePart[filePart.length - 1];
I think we should try to use:
https://nodejs.org/api/path.html#pathdirnamepath
https://nodejs.org/api/path.html#pathbasenamepath-suffix

2023-09-12 17:33 UTC, joaquimrocha commented on frontend/src/i18n/locales/keys.test.ts
> +      }
Replace `wordMap[lang][i]` by `currentWord` for readability.

2023-09-13 14:29 UTC, joaquimrocha commented
> I wonder if for the mechanism we can utilize the context field for languages that may reuse words? https://www.i18next.com/translation-function/context

Yes. This makes sense. Thanks.

2023-09-13 17:40 UTC, joaquimrocha requested changes
Looking good but found a few issues running it.

2023-09-13 17:40 UTC, joaquimrocha commented on frontend/src/i18n/locales/keys.test.ts
This and the allowlist.json files will lead to issues because they're placed in the `locales` folder, which is destined for locale folders only. Run `make i18n` to see what I mean.
Please move these files one level up (to `frontend/src/i18n`) and also I think this test file should be called `index.test.ts` as it's the main test we have for this i18n module.

2023-10-03 11:28 UTC, joaquimrocha commented
I have updated the test to fix a few corner cases (it was not discarding the "old" translations files, and it was not checking whether the same keys were being checked in the same file).
Then I added a commit to reduce the number namespaces, deduplicated translation strings, and added translations.

Maybe @illume can give an extra look.

2023-10-04 17:19 UTC, illume commented
Why are all the namespaces gone? This makes it much harder to get context on what the strings are for, and where to see the text in app.

2023-10-05 11:39 UTC, joaquimrocha commented
> Why are all the namespaces gone? This makes it much harder to get context on what the strings are for, and where to see the text in app.

It explained in #1426 .
Using multiple namespaces makes it very easy to use the wrong namespace and then we get duplicated strings for the same translation, which multiplies the translation work. It's also less convenient to translate strings in different files.
Besides, if context is what's needed for each string, then adding the context to the translation function makes it more convenient (`t('Desired', {context: 'pods'})`).

I believe maintaining the i18n as it is and trying to get anywhere close to 100% coverage represents a big effort that I find hard to justify. So this PR and the #1429 aim at simplifying the process. My concerns are whether having all these strings together represents a performance issue for the application UX, but even if cases of ambiguous translations arise, having it all together makes for an easier fix for those when they happen.

2023-10-12 16:23 UTC, illume approved these changes
👍 thanks

2023-10-12 16:23 UTC, illume commented on frontend/src/i18n/ThemeProviderNexti18n.tsx
> +    ['sidebar', 'translation', 'glossary', 'auth', 'resource', 'notifications'],
Some of these should be removed.

2023-10-18 08:40 UTC, joaquimrocha approved these changes

2023-10-18 08:40 UTC, merged