Update Tabs.tsx
headlamp-k8s/headlamp pull request #1601
Opened 2023-12-16 06:32 UTC by RISHIKESHk07

UPDATED THE Tabs.tsx with TSDoc comments
issue #976 
Signed-off-by: RISHIKESHk07 <rishikeshkuppala@googlemail.com>

2023-12-26 16:25 UTC, RISHIKESHk07 commented
@anshu8912 any changes ? need some help on the checks not sure how to resolve it .....

2024-01-03 18:49 UTC, joaquimrocha requested changes
Thanks for this PR @RISHIKESHk07 .
Please rename the commit as: `frontend common/Tabs.tsx: Add code docs`

2024-01-10 11:39 UTC, RISHIKESHk07 commented
Hey @joaquimrocha , sorry for the late reply i did change the commit message , anything else i should do the checks are failing , not sure where it went wrong

2024-01-11 15:52 UTC, joaquimrocha commented
> Hey @joaquimrocha , sorry for the late reply i did change the commit message , anything else i should do the checks are failing , not sure where it went wrong

Hi @RISHIKESHk07 . Yes. The DCO is failing because the commit needs to be signed off by you. That's done by using `git commit -s`. It has to be signed off by an email that you have associated with your account on Github.

And now you also need to rebase this branch.

2024-01-12 09:22 UTC, RISHIKESHk07 commented
@joaquimrocha thanks for the help , did the changes , anything i need to correct?

2024-01-12 15:06 UTC, joaquimrocha commented
You have one extra commit which I believe is due to not rebasing or a problem in doing so. Can you make sure that only your single commit is in the PR?

2024-01-13 04:37 UTC, RISHIKESHk07 commented
@joaquimrocha i had to merge the original repo with my main branch (changes were on the main  ), had some conflicts with @yolossn commit I did resolve it , any idea what I should try doing , thanks

2024-01-14 13:15 UTC, RISHIKESHk07 commented
Got this for the lint (make frontend-lint command ),
Oops! Something went wrong! :(

ESLint: 8.56.0

ESLint couldn't find the config "@kinvolk" to extend from. Please check that the name of the config is correct.

The config "@kinvolk" was referenced from the config file in "/home/intelliagent-19/headlamp/frontend/package.json".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

make: *** [Makefile:80: frontend-lint] Error 2

2024-01-18 06:31 UTC, RISHIKESHk07 commented
@joaquimrocha thanks , got it to work

2024-01-22 16:54 UTC, joaquimrocha commented
Hmm, the test failed because you don't have a kubeconfig file?
What OS are you using?

2024-01-22 17:23 UTC, RISHIKESHk07 commented
@joaquimrocha  linux mint 20.3

2024-01-29 16:53 UTC, RISHIKESHk07 commented
@joaquimrocha any doc on the website i could follow ....

2024-01-30 17:45 UTC, yolossn commented
> @joaquimrocha thanks , got it to work , i tried to make backend-test as well but got a error because i did not have the config file under /.kube , how can i set this up ?

This is happening because the backend is expecting a kubeconfig in the directory. To solve for this install minikube or other local kubernetes solutions like KIND. On a side note, Since you didn't make any changes to the backend, I don't think there is a need to run the backend-test locally.

2024-01-30 17:47 UTC, yolossn commented on frontend/src/components/verticalPodAutoscaler/VPAList.stories.tsx
> +import { Meta } from '@storybook/react/types-6-0';
From the logs of the failing tests looks like this change is the issue. Either use the old package itself or include the changes to package.json also in the commit.

2024-02-15 11:03 UTC, joaquimrocha commented
@RISHIKESHk07 , the commit is still looking like it's not the changes you wanted to add. Do you need help with this? If you submit a new branch, regardless of the format, we can also take it ourselves and redo the commit, setting you as co-author.

2024-02-16 06:40 UTC, closed without merging

2024-02-16 07:24 UTC, RISHIKESHk07 commented
@joaquimrocha i found that my commit got merged with a @yolossn  commit so it was creating a problem , maybe its better to create a new PR ? , Would that be problem ?

2024-02-16 18:09 UTC, joaquimrocha commented
> @joaquimrocha i found that my commit got merged with a @yolossn commit so it was creating a problem , maybe its better to create a new PR ? , Would that be problem ?

Hi @RISHIKESHk07 . The problem was not the PR, it was the commit. If you create a new commit and force push it to the branch you had created, it'd be fixed as well. But it is also fine to do it in a new PR.