Some smaller improvements
headlamp-k8s/headlamp pull request #1615
Opened 2023-12-18 19:11 UTC by farodin91

secret:
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/7e507aa7-18ae-4845-9746-47f47639a69f)
configmap:
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/b49c743e-cd7d-4986-a25e-0674bb8b4bd9)

pvc:
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/678869b1-9780-4d0a-ad82-5ee82264184f)
pv:
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/a132001f-8f58-44d5-8912-88b8a371a0e0)

Sidebar
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/01c67cfe-4ef2-4de1-860a-7adddda89367)
![image](https://github.com/headlamp-k8s/headlamp/assets/1159212/791ddafc-8d22-4374-a4fe-a504742d2aff)

2023-12-20 09:50 UTC, farodin91 commented
I will split into multiple PRs

2023-12-20 11:02 UTC, farodin91 commented
See #1620 and #1619

2024-01-08 11:19 UTC, joaquimrocha requested changes

2024-01-08 11:19 UTC, joaquimrocha commented on frontend/src/i18n/locales/de/glossary.json
> +  "Volume Claims": "",
I think these were mistakenly rewritten as empty (same for all translation languages).

2024-01-11 11:47 UTC, farodin91 commented
@joaquimrocha I have updated the translation and reorder a bit workloads.

2024-01-12 15:36 UTC, joaquimrocha approved these changes

2024-01-12 15:36 UTC, merged