frontend: cleanup storage section
headlamp-k8s/headlamp pull request #1620
Opened 2023-12-20 10:59 UTC by farodin91

* reorder lists to look the same
* status label on PV and PVC
* links to storageclass in details
* add basic tests

2024-01-02 18:45 UTC, joaquimrocha approved these changes
LGTM though I left a comment to improve the use of types.
For similar PRs, we should keep in mind having atomic commits instead.

2024-01-02 18:45 UTC, joaquimrocha commented on frontend/src/components/storage/ClaimList.stories.tsx
> +  const noVolumeNamePVC = _.cloneDeep(BASE_PVC) as KubePersistentVolumeClaim;
Declaring the type of the BASE_PVC as it had for basePVC is better than using `as` since `as` can mask any missing members here.

2024-01-02 18:46 UTC, joaquimrocha requested changes
Meant to request the changes for the typing as mentioned.

2024-01-03 07:11 UTC, farodin91 commented
I'll try to fix on Friday.

2024-01-03 07:13 UTC, farodin91 commented
> For similar PRs, we should keep in mind having atomic commits instead.

Just splitting into smaller units, or?

2024-01-03 08:55 UTC, joaquimrocha commented
> > For similar PRs, we should keep in mind having atomic commits instead.
> 
> Just splitting into smaller units, or?

Atomic as in: a commit should be related to one fix or one feature that's contained in that commit, rather than mixing different features/fixes in one bigger commit.

2024-01-04 21:40 UTC, farodin91 commented
@joaquimrocha splitted into multi atomic PRs and typing fixed.

2024-01-08 11:12 UTC, joaquimrocha requested changes
Thanks @farodin91 for splitting things up.
I made some comments about the commit format and others. I know these may sound a bit nitty, but I hope they make sense to you as making things closer in format will make for an easier radibility/bug-fix later on.

2024-01-08 11:12 UTC, joaquimrocha commented on frontend/src/components/storage/VolumeDetails.stories.tsx
Not to be pedantic here, but normally our commit titles are like:
```
frontend storage/VolumeDetails: Add link to StorageClass

Also adds Storybook coverage.
```

This could also be two commits: Add link  + Add storybook coverage, but it's okay.

2024-01-08 11:12 UTC, joaquimrocha commented on frontend/src/components/storage/ClaimList.stories.tsx
For future reference, we try to keep commit titles (and body) under 72 chars length. See also my other comment about the commit message referring to the main thing a commit does, and that the body can be used to elaborate on secondary things.

2024-01-08 11:12 UTC, joaquimrocha commented on frontend/src/components/storage/storyHelper.ts
Ah, I see you added the fix here.
As a good practice, we don't add commits fixing things introduced in the very same PR. The reasons for these are:
1. Makes reviewing more difficult as we tend to review commit by commit.
2. Adds "wrong" changes to the history, so if we do a git bisect, we may run into problematic commits because they get fixed in a later commit. While this is inevitable throughout the development, we can avoid it in PRs.

Hope it makes sense.

2024-01-08 12:56 UTC, farodin91 commented
@joaquimrocha I tried to cleanup commits.

2024-01-08 19:24 UTC, joaquimrocha approved these changes
LGTM! Thanks a lot @farodin91 for having changed the commits/format.
@illume , the Mac build is failing on an svgo dep. Weird that it's the only one that has failed.

I am tempted to just merge this and figure out the build later as it seems unrelated, but would like your opinion.

2024-01-08 21:20 UTC, farodin91 commented
I would say it's a timeout issue or. It could help to restart of the failed job?

2024-01-09 13:14 UTC, farodin91 commented
@joaquimrocha  rebase did work.

2024-01-11 10:11 UTC, merged