frontend Notifications/List.tsx: Fix and reformat styles
headlamp-k8s/headlamp pull request #1674
Opened 2024-01-25 18:48 UTC by vyncent-t

2024-01-25 21:07 UTC, vyncent-t commented
## Dev notes

- _This push is a solid base, I have tweaked the vw for each size to not clip or run into other columns (ignore the colors)_
- _I am using the CellProps and a custom style map to put in custom style changes to achieve this_ 
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/a8891777-2948-4e0d-8c89-a46c7e44f446)
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/a8354389-f43a-4cae-895a-fe6c3919a134)


- _Currently using useEffect to rerender when any screen size changes, when it changes it grabs a new view size for the message column_ 
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/f1f1a9d3-ba9e-4d06-828e-a440d2fa9970)



- The comps are responsive
**Large**
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/6a1eba69-e717-4ce5-9bbe-18de2b8e918e)

**Medium**
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/e3ea078d-d0c3-43f0-9411-befe6ac5199a)

**Small**
![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/10c16cd9-2edb-4140-a691-c73ceeafa1c6)

2024-01-30 19:47 UTC, vyncent-t commented
## Dev note

- [x] Added context links to the notifications view

![image](https://github.com/headlamp-k8s/headlamp/assets/78232183/a8c46d39-57a8-4d88-a255-2320a0eba612)

2024-02-15 13:29 UTC, joaquimrocha requested changes
The PR approach has an issue with cutting off parts of the table. See the screenshot below:

![Screenshot showing the prob](https://github.com/headlamp-k8s/headlamp/assets/1029635/3dfff478-def7-49f7-ad7c-ca3fd262878e)

I think we can accomplish a good result with a less engineered effort here. Namely by using `gridTemplate:` for each column as adequate. The text column should just have `auto` so it expands, and the rest should have a `min-content`.
The div around the text column should not have the ` width={'30vw'}`, otherwise it looks artificially cut.

2024-02-26 12:04 UTC, joaquimrocha approved these changes
LGTM. The mobile version is not functional but we should fix that in a different occasion anyway.

2024-02-26 12:06 UTC, merged