frontend: Fix visibility of Sidebar Elements and Navigation Tabs
headlamp-k8s/headlamp pull request #1720
Opened 2024-02-15 22:58 UTC by tazo90

This PR fixes [#1719 ](https://github.com/headlamp-k8s/headlamp/issues/1719).

### Problem 1: Sidebar elements not visible

Before:
![sidebar-before](https://github.com/headlamp-k8s/headlamp/assets/3165572/55596288-2ff5-44b4-9ac8-2e80196be268)

After:
![sidebar-after](https://github.com/headlamp-k8s/headlamp/assets/3165572/9ac5f1e2-b9fb-46aa-b9bc-8a82f87e77cf)

---

### Problem 2: Invisible Navigation Tabs

Before:
![navigation-tabs-before](https://github.com/headlamp-k8s/headlamp/assets/3165572/4cc61b7f-eb55-483f-86a4-8ef36d1ce730)

After:
![navigation-tabs-after](https://github.com/headlamp-k8s/headlamp/assets/3165572/86fd3c36-49bd-4f80-aeba-738f2cc9f74f)

2024-02-29 16:54 UTC, joaquimrocha commented
Hey @tazo90 , thanks for this PR. I have noticed that the logo looks broken with it though (maybe due to the updates we had in the meanwhile):
![screenshot](https://github.com/headlamp-k8s/headlamp/assets/1029635/43220517-e01b-4a15-a926-466f24cdb671)

I will review the code now.

2024-02-29 17:07 UTC, joaquimrocha requested changes
Thanks again @tazo90 . I left some comments on how to improve this PR.

2024-02-29 17:07 UTC, joaquimrocha commented on frontend/src/components/Sidebar/Sidebar.tsx
> +export const topBarHeight = 64;
The problem is that the sidebar is set from the top of the screen, without having the toolbar before it.
A more future-proof way of fixing this issue is to see what the normal case is doing: Adding a Box with the toolbar style mixin (look for the use of the `toolbar` class).

2024-02-29 17:07 UTC, joaquimrocha commented on frontend/src/components/Sidebar/NavigationTabs.tsx
This merge commit should be avoided by rebasing your changes + solving the conflicts.

2024-02-29 17:07 UTC, joaquimrocha commented on frontend/src/components/App/Home/__snapshots__/RecentClusters.stories.storyshot
Snapshots should be added to the commits that introduce them (this avoids e.g. bisecting into a commit that doesn't test correctly because the snapshot is missing).

2024-02-29 17:07 UTC, joaquimrocha commented on frontend/src/i18n/locales/de/frequent.json
We no longer have the `frequent` namespace. Only glossary + translation (default).

2024-03-28 23:28 UTC, tracetechnical commented
@tazo90 , have you had any more time to work on this? Really excited for this PR to get in so that headlamp is usable on mobile for me

2024-06-20 14:23 UTC, joaquimrocha commented
Closing in favor of #2062 .

2024-06-20 14:23 UTC, closed without merging