headlamp-plugin: Limit update checks to daily
headlamp-k8s/headlamp pull request #1941
Opened 2024-05-01 21:57 UTC by skoeva

This change lets headlamp-plugin only check for updates once daily and institutes a `force-check` option for users to force an update check.

Fixes: #1899

2024-06-13 14:43 UTC, joaquimrocha requested changes
Besides the comments about the logic. I think this PR is doing 2 things: replacing the function that checks for the latest pkg version + limiting the checks.

2024-06-13 14:43 UTC, joaquimrocha commented on plugins/headlamp-plugin/bin/headlamp-plugin.js
> +      : null;
This logic means lastCheckTime can be set as null, and then on line 282 it's used in arythmetic.

2024-06-13 14:43 UTC, joaquimrocha commented on plugins/headlamp-plugin/bin/headlamp-plugin.js
> +    }
Will this command still hang while it's started?

2024-06-13 14:43 UTC, joaquimrocha commented on plugins/headlamp-plugin/bin/headlamp-plugin.js
> +async function getLatestPkgVersion() {
You introduced a new way to check for the latest version. But the previous function is still used for the upgrade. Should we unify this?

2024-06-19 11:36 UTC, illume requested changes
From this comment in the issue: https://github.com/headlamp-k8s/headlamp/issues/1899#issuecomment-2099965074

> It could be made async, so it doesn't block the user getting work done.
>
> If the check is done async, then it can show the message some moments later. This avoids having state, and has the benefit that it isn't slow once a day. The user is never slowed down in their work.

Currently doing `npm start` with this branch will do the check in an async fashion never block the user. So I think all of the last check stuff is not necessary.

The main goal of not blocking the user is achieved with the code:

```ts
  informIfOutdated().catch(error => {
    console.error('Failed to check for updates:', error);
  });
```

So please keep that `informIfOutdated()` call, and remove all the `lastCheckTime` code and the `force-check` code.

2024-06-20 17:21 UTC, skoeva commented
@illume I see, thanks for the fix! I think this makes sense since I noticed issues with performing the `getNpmOutdated()` code async, I can remove the debug lines and squash this now

2024-06-21 09:14 UTC, joaquimrocha approved these changes

2024-06-21 09:15 UTC, merged