Remove unnecessary fields from the editor
headlamp-k8s/headlamp pull request #2036
Opened 2024-06-11 15:01 UTC by Guilamb

A first draft to resolve #2032. I believe there might be a better way to do this.

I've removed the Status and ManagedFields fields from the code when making the editor dialog.

Fixes: #2032
Signed-off-by: guilhane <guilhane.bourgoin@orange.com>

2024-06-11 17:45 UTC, joaquimrocha commented
Hey @Guilamb . 
I think a more extensible way we could implement this is to have a function called `getEditableObject` in the `KubeObject` class. 
This alone would allow flexibility enough that each class can just implement what the editable version of their objects looks like.

However, we can make this even more powerful by adding a getter called `readOnlyFields` which returns a list of `jsonPath` paths. So we use this list in the base `getEditableObject` to remove any read-only fields. Meaning that k8s classes just have to define the list of readonly fields.

This way, we have enough flexibility to define which fields are readonly and also what the editable object looks like.

Can you implement this?

I am sure that there's a way to extract which of these fields are read-only from the server API, but we can connect something like that later.

2024-06-12 10:21 UTC, Guilamb commented
Hi @joaquimrocha,

I'll try to implement this.

To get the read-only fields, the solution I've found so far is to get the OpenAPI schema and check if there is a "read-only" in the description.

I've generated a Python script to test this solution, and it seems to work. However, if someday someone writes in a description that a field is "not read-only," it would still be added to the read-only fields 🫤. I'm not sure how likely this scenario is to happen.https://gist.github.com/Guilamb/aecd34fe815d60a343dfe57fd795fda3

Additionally, metadata.managedFields doesn't appear because the description states:
``` Markdown
ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. 
This is mostly for internal housekeeping, and `users typically shouldn't need to set or understand this field.`
 A workflow can be the user's name, a controller's name, or the name of a specific apply path like \"ci-cd\". 
The set of fields is always in the version that the workflow used when modifying the object.
```

I've looked at how other tools have handled this problem, and from what I saw, for the managedFields they are simply removed from display. I've looked at Backstage (https://github.com/backstage/backstage/issues/14177) and kubectl (https://github.com/kubernetes/kubernetes/pull/96878).

2024-06-12 12:02 UTC, joaquimrocha commented
Thanks. It's fine to go without checking the API server. The solution I proposed with the 2 functions in the base class + overriding them in classes that need it, should be flexible enough.

2024-06-19 11:02 UTC, joaquimrocha requested changes
Left a few comments.
Feel free also to squash the commits + force push.

2024-06-19 11:02 UTC, joaquimrocha commented on frontend/src/lib/k8s/crd.ts
> +  readOnlyFields = ['managedFields'];
Should be given as JSONPath.

2024-06-20 09:04 UTC, Guilamb commented
I will squash those commits, if the changes made are correct

2024-07-01 13:59 UTC, joaquimrocha requested changes
Thanks @Guilamb . It's almost there. Please check my review.

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/components/common/Resource/EditorDialog.tsx
> +
Please do not add changes like this that are unrelated.

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/components/common/Resource/EditorDialog.tsx
> -
Please do not add changes like this that are unrelated.

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +    static get readOnlyFields(): JsonPath<T>[] {
Add a newline before this function.

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +    getEditableObject() {
Add a newline before this function.

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +      })(code);*/
Please remove unused code instead of commenting it out.

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +      const code = this.jsonData ? cloneDeep(this.jsonData) : '{}';
The type of code will be different depending on whether we have jsonData or not (i.e. the else part should be {}, not '{}').

2024-07-01 13:59 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +      string;
Do we need all this typing? Maybe @sniok can help with simplifying this.

2024-07-04 09:42 UTC, Guilamb commented
Thank you for the feedback, I've tried another way to define JsonPath type, to make it shorter.
If every things ok, just send me a message by slack or put a comment here, and I'll squash all the commit together 👍

2024-07-11 16:52 UTC, joaquimrocha reviewed
I found a bug in the code, and a change I requested which actually doesn't make sense. After this I think you can squash all commits as the PR is ready. Please give it a commit message like:
```
frontend: Allow KubeObjects to set which parts of them are editable

This PR adds a new var to KubeObject classes to declare fields that shouldn't be
considered when editing the files. It also sets a new getEditableObject method
that uses these fields and removes them from an object clone and is used with
the Editor.
```

It would be nice if the code that adds the fields to the CRD is a different commit, but it's simple enough that you can keep it the same. If you keep them together, please add a new paragraph after the above and mention that CRD is also getting its list of readonly fields.

2024-07-11 16:52 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +      const fieldsToRemove = this._class().readOnlyFields;
We should check if fieldsToRemove is undefined as this leads to an error when trying to run the foreach later in this block.
If !fieldsToRemove, we should just return the this.jsonData.

2024-07-11 16:52 UTC, joaquimrocha commented on frontend/src/lib/k8s/cluster.ts
> +    static get readOnlyFields(): JsonPath<T>[] {
I was wrong about asking for this to be a getter, as overriding this in the subclasses, as you did, requires declaring the _readOnlyFields, which is not a good practice. Let's turn _readOnlyFields into readOnlyFields and make it public.

2024-07-25 12:54 UTC, joaquimrocha approved these changes

2024-07-25 12:54 UTC, merged