winget: Updates  manifest schema
headlamp-k8s/headlamp pull request #2192
Opened 2024-07-23 19:58 UTC by vyncent-t

2024-07-24 06:26 UTC, illume commented
Something is very wrong here with the commit as there are 159 files changed. Seems like a rebase/merge issue.

2024-07-24 21:54 UTC, vyncent-t commented
may need to downgrade the the prettier to not have this format error

2024-07-25 08:43 UTC, illume commented
@vyncent-t Please rebase? 

Also, please do the formatting changes in a separate commit (or PR).

2024-07-25 09:15 UTC, joaquimrocha commented
I have fixed the format issues, but I don't think this is all there is to update the format to 1.6.
I haven't tested with the validator, but it just looks different from these [changes](https://github.com/microsoft/winget-pkgs/pull/164117/files) (maybe some of them aren't needed, like release notes, but we should add the others).

2024-07-25 11:00 UTC, illume approved these changes
Thanks 👍

2024-07-25 11:01 UTC, illume requested changes
I missed the comments from Joaquim about needed changes.

2024-07-25 13:18 UTC, vyncent-t commented
Just compared the changes for 1.6.0 schema for each of these to what is in 1.5.0 and it doesn't seem to have any more additional required fields to be added
- [installer](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md)
- [locale](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/locale.md)
- [version](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/version.md)

and the only difference I can see is that someone must have changed [a locale field ReleaseNotes](https://github.com/headlamp-k8s/winget-pkgs/blob/ee7bb7ade7ed894b06373f0ad62f271781d38f66/manifests/h/Headlamp/Headlamp/0.24.1/Headlamp.Headlamp.locale.en-US.yaml) since its not in the the previous winget schemas for locale nor does it generate automatically when the script runs, although I can't find the source of that change like we were able to find the source of the change [for the displayVersion being removed](https://github.com/microsoft/winget-pkgs/pull/157930#issuecomment-2173915577) which has been removed here.

other than that there aren't any differences that I can spot between the optional and required fields already used here

2024-07-25 18:19 UTC, vyncent-t commented
I think there is an unsigned commit that is throwing the error?

![image](https://github.com/user-attachments/assets/377bf175-1f0b-4bcd-89af-3e2af2672190)

2024-07-26 09:34 UTC, joaquimrocha commented
The problem was the mismatch between the signoff and the author of the commit. It's fixed now, but we did talk about having the format closer to what was in that 0.24.1 version I had to modify this week.

2024-07-26 13:34 UTC, vyncent-t commented
I think I may have pushed the windows copy on mistake (the one I have to create for validation)

pushing the linux side one now

2024-07-26 13:45 UTC, vyncent-t commented
current changes should be the same as the ones that are from 0.24.1

https://github.com/microsoft/winget-pkgs/blob/master/manifests/h/Headlamp/Headlamp/0.24.1/Headlamp.Headlamp.installer.yaml

https://github.com/microsoft/winget-pkgs/blob/master/manifests/h/Headlamp/Headlamp/0.24.1/Headlamp.Headlamp.locale.en-US.yaml

https://github.com/microsoft/winget-pkgs/blob/master/manifests/h/Headlamp/Headlamp/0.24.1/Headlamp.Headlamp.yaml

2024-07-29 21:24 UTC, joaquimrocha approved these changes

2024-07-29 21:24 UTC, merged