app: Use shell to run headlamp-server
headlamp-k8s/headlamp pull request #2248
Opened 2024-08-20 11:20 UTC by illume

This takes care to try extra hard to kill headlamp-server.

### testing

The headlamp-server is not running after the app closes.

- [x] linux
- [ ] windows
- [ ] mac

2024-08-21 09:46 UTC, joaquimrocha commented
I have tested this PR and there is a regression with these changes.
How to reproduce:
1. Run a headlamp-server process (`make run-backend`)
2. Build the app in unpacked mode: `cd app && npm run package -- --dir`
3. Run the app (`cd app; ./dist/linux-unpacked/headlamp`)
4. When prompted about what to do since a server is already running, choose `Quit` -> observe the log coming from an infinite loop and the app not getting closed.

I think this may be because of doing the closing logic on before-quit rather than quit but I am not sure. On main this doesn't happen.

2024-08-21 09:47 UTC, joaquimrocha requested changes
Asking for changes given the regression found. Maybe if the signal is changed back, we should document that it needs to be that signal and how to test it.

2024-08-22 16:45 UTC, illume commented on backend/cmd/headlamp.go
> +	// Log all environment variables
This is just for debugging, I'll remove before merge.

2024-08-23 17:31 UTC, illume commented
I added logging to headlamp-server so you can check the PATH and other env vars are there. It creates an `/tmp/envfiles.txt` with the environment variables in there.

Can you please run this and confirm the env vars are passed through now? Then I will remove the `/tmp/envfiles.txt` writing code from the PR.
(it works for me on my macos)

2024-08-26 10:00 UTC, joaquimrocha commented
@illume I have tested it again and the issue with quitting the app is gone.
The env vars declared in the terminal (`MY_ENV_VAR=test npm run dev`) do indeed pass over to the generated file. As expected, running from Finder will not have anything close to the env vars we have when running from terminal.

2024-08-26 10:03 UTC, illume commented
> As expected, running from Finder will not have anything close to the env vars we have when running from terminal.

Are you sure? On my system the PATH output to `/tmp/envfiles.txt` is the same as the PATH in my terminal. Additionally, the other env variables are there.

2024-08-26 17:40 UTC, illume commented
@joaquimrocha Now it is working for me with a MacOS user that is using zsh.

(Note, use .zshrc instead of .profile because zsh doesn't look at .profile)

2024-08-27 09:19 UTC, illume commented
fixed formatting

2024-08-27 10:27 UTC, illume commented on app/electron/main.ts
> +  if (typeof shell === 'string') {
Test zsh on Ubuntu.

2024-08-27 10:27 UTC, illume commented on app/electron/main.ts
> +    return spawn(shell, ['--login', '-ic', '-c', serverFilePath].concat(serverArgs), {
"-ic" has redundant "c".

2024-08-27 10:28 UTC, illume commented on app/electron/main.ts
> +    return spawn(shell, ['--login', '-ic', '-c', serverFilePath].concat(serverArgs), {
Wrap in a try/catch and if it fails try to start normally.

2024-08-27 12:03 UTC, illume commented on backend/cmd/headlamp.go
> +// WriteEnvToFile writes all environment variables to a temporary file.
This is just for testing, it will be removed after testing is complete.

2024-08-27 12:05 UTC, illume commented
@joaquimrocha changes we talked about where done.
I tested this again with MacOS with bash and zsh, and also Ubuntu with zsh.

Also added another fix for zsh showing an interactive shell if zsh is not installed properly (like if the user has no .zh files).

2024-08-27 13:39 UTC, illume commented
The `kill ESRCH` is because the process is already terminated. I should catch that error and prevent the error message being shown.

(I'm assuming the headlamp-server was not running after quit, and that this was on MacOS?)

2024-08-27 15:15 UTC, joaquimrocha approved these changes
WFM now. Please remove the env file creation code and merge.

2024-08-27 15:40 UTC, yolossn commented
I tested and this works for me but I was able to get it to work just by adding the proper env to the spawn options without having to use the shell to run the backend, IMHO using the shell when spawning is complicating the termination process.

Providing a git diff below for reference.
```
diff --git a/app/electron/main.ts b/app/electron/main.ts
index 0991c753..5b7ccf55 100644
--- a/app/electron/main.ts
+++ b/app/electron/main.ts
@@ -453,6 +453,42 @@ class PluginManagerEventListeners {
   }
 }
 
+function getShellEnv(): NodeJS.ProcessEnv {
+  if (process.platform === 'win32') {
+    return process.env;
+  }
+
+  let shell = process.env.SHELL || '/bin/sh';
+  if (process.platform === 'darwin') {
+    try {
+      shell = userInfo().shell || '/bin/zsh';
+    } catch (error) {
+      shell = '/bin/zsh';
+    }
+  }
+
+  try {
+    const env = { ...process.env, DISABLE_AUTO_UPDATE: 'true' };
+    const result = execSync(`${shell} -ilc 'env'`, {
+      encoding: 'utf8',
+      timeout: 10000,
+      env,
+    });
+
+    const envVars = result.split('\n').reduce((acc, line) => {
+      const [key, value] = line.split('=', 2);
+      if (key && value) acc[key.trim()] = value.trim();
+      return acc;
+    }, {} as NodeJS.ProcessEnv);
+
+    console.log('Shell environment variables:', envVars);
+    return { ...process.env, ...envVars };
+  } catch (error) {
+    console.error('Failed to get shell environment:', error);
+    return process.env;
+  }
+}
+
 function startServer(flags: string[] = []): ChildProcessWithoutNullStreams {
   const serverFilePath = isDev
     ? path.resolve('../backend/headlamp-server')
@@ -488,11 +524,14 @@ function startServer(flags: string[] = []): ChildProcessWithoutNullStreams {
   serverArgs = serverArgs.concat(flags);
   console.log('arguments passed to backend server', serverArgs);
 
-  // We run detached but not in shell, otherwise it's hard to make sure the
-  // server process gets killed. When changing these options, please make sure
-  // to test quitting the app in the different platforms and making sure the
-  // server process has been correctly quit.
-  const options = { detached: true };
+  const shellEnv = getShellEnv();
+  const options = {
+    detached: true,
+    env: shellEnv,
+    shell: true,
+  };
+
+  console.log('Server process options:', options);
 
   return spawn(serverFilePath, serverArgs, options);
 }
```

2024-08-27 15:50 UTC, illume commented
@yolossn after running into trouble parsing environment variables I decided to go this way. There are a number of edge cases with environment variables. Additionally there are differences with different shells.

2024-08-27 15:57 UTC, illume commented
Removed `WriteEnvToFile("envfiles.txt")` which was just added for testing.

2024-08-28 07:26 UTC, illume commented
@yolossn Hey hey. Can you please see review notes I left in [app: Improve shell env capture for better cross-platform support by yolossn · Pull Request #2271 · headlamp-k8s/headlamp (github.com)](https://github.com/headlamp-k8s/headlamp/pull/2271)
 
I think it's right that it's better to not use a shell to launch. Let me know if you want to continue to fix these things in your PR, or I can also switch back to reading env vars in this PR?

2024-08-28 07:39 UTC, closed without merging