frontend: Install tar and sync to headlamp-plugin
headlamp-k8s/headlamp pull request #2325
Opened 2024-09-11 18:41 UTC by skoeva

This change addresses the plugins test failure in the CI.

Fixes: #2324

#### Testing
Tested on issue #1996 in [this commit](https://github.com/headlamp-k8s/headlamp/commit/ddd6c4a3cc49b67878bdfe05af285a37c9c6eb06).
- [ ] Run `make plugins-test` and ensure that it passes

2024-09-11 19:52 UTC, vyncent-t commented
it would be good to detail out the reproduction steps, I'm assuming its meant to be ran at the root level of the project.

I also seem to be hitting a different error than the one you have in the original issue

![image](https://github.com/user-attachments/assets/44249906-f7ea-4da9-beac-417a5f0efe2d)

2024-09-11 19:57 UTC, vyncent-t commented
also, I would try

- pull from main for the most recent changes
- remove the node modules folders in the frontend and plugins
- run npm i for frontend and then npm i for the plugins
- run make plugins-test again

2024-09-12 07:40 UTC, sniok requested changes
nice fix, thanks! just remove tar from frontend and we can merge this

2024-09-12 07:40 UTC, sniok commented on frontend/package.json
> +    "tar": "^7.4.3",
tar is only missing from the plugins/headlamp-plugin, no need to add to the frontend

2024-09-12 14:52 UTC, sniok approved these changes

2024-09-13 09:17 UTC, merged