frontend: Add feature to view deploy logs
headlamp-k8s/headlamp pull request #2581
Opened 2024-11-18 02:59 UTC by knrt10

This adds feature to view all the pods of pods in a deployment rather than going to a specific pod.

Fixes: #2552

### Testing

- Create a deployment `kubectl create deployment nginx --image=nginx`
- Run the app and navigate to the deployment
- Click on the logs button to view the logs of all the pods in the deployment

### Screenshots

<img width="1715" alt="Screenshot 2024-11-18 at 8 17 47 AM" src="https://github.com/user-attachments/assets/1c93a933-6183-4a5e-bb44-90c1363368af">
<img width="1405" alt="Screenshot 2024-11-18 at 8 18 24 AM" src="https://github.com/user-attachments/assets/d78384ae-f051-4a96-a9a4-d1a2cbe7775d">

2024-11-18 03:52 UTC, knrt10 commented
So weird, I ran the tests locally, updated snapshots, wonder why it is still failing 🤔

2024-11-18 09:50 UTC, knrt10 commented
Changing some UX for this

2024-11-29 09:31 UTC, knrt10 commented
Updated, please review

2025-01-03 08:33 UTC, illume reviewed
I think the error states could be added for if any request fails. Left a couple of notes in the spots I think they could be handled.

Maybe not in this PR... but it would probably good to add a loading state? I'm not sure if the logs already have a loading state? (I didn't look).

Adding some states into a LogsButton.stories.tsx would be nice to have.

2025-01-03 08:33 UTC, illume commented on frontend/src/components/common/Resource/LogsButton.tsx
> +      const fetchedPods = await getRelatedPods();
There should be error handling for this. With a try/catch, and telling the user that something went wrong if something does.

2025-01-03 08:33 UTC, illume commented on frontend/src/components/common/Resource/LogsButton.tsx
> +      const response = await request(
There should be error handling for this. With a try/catch, and telling the user that something went wrong if something does.

2025-01-03 08:47 UTC, illume commented on frontend/src/components/common/Resource/LogsButton.tsx
> +        label="Follow"
Label should be translated.

2025-01-03 08:47 UTC, illume commented on frontend/src/components/common/Resource/LogsButton.tsx
> +        label="Timestamps"
Label should be translated.

2025-01-20 05:33 UTC, knrt10 commented
Updated the PR, please review

2025-01-20 05:36 UTC, knrt10 commented
> Maybe not in this PR... but it would probably good to add a loading state? I'm not sure if the logs already have a loading state? (I didn't look).

I checked and can confirm that there isn't currently any loading state implemented for the logs

> Adding some states into a LogsButton.stories.tsx would be nice to have.

You're right - it would be good to add loading states for:
- Initial pod fetching
- Log stream initialization
- Reconnection attempts

But I guess we can do it in a separate PR. WDYT?

2025-01-22 13:01 UTC, joaquimrocha requested changes

2025-02-03 05:34 UTC, knrt10 commented on frontend/src/components/common/Resource/LogsButton.tsx
> +              });
Modifed it to parse logs in chunks for better performance.

2025-02-03 05:35 UTC, knrt10 commented on frontend/src/components/common/Resource/MainInfoSection/MainInfoSectionHeader.tsx
> +          break;
Done, now RS and DS also have logs button

2025-02-03 05:35 UTC, knrt10 commented on frontend/src/components/common/Resource/LogsButton.tsx
> +      {pods.length && showLogs && (
Fixed

2025-02-21 17:38 UTC, joaquimrocha approved these changes

2025-02-21 17:41 UTC, joaquimrocha commented
Nice work. I think we can iterate later to add things like showing all containers' logs too.

2025-02-21 17:52 UTC, merged