frontend Sidebar: Improve performance by moving isSelected logic to the parent component
headlamp-k8s/headlamp pull request #2638
Opened 2024-12-05 10:41 UTC by sniok

Blocked by #2590

With this change only items that were updated will rerender

2024-12-30 11:48 UTC, illume requested changes
Thanks.

I left some notes.

Can you please leave in the PR description how to test?

2024-12-30 11:48 UTC, illume commented on frontend/src/components/Sidebar/SidebarItem.tsx
>    /** The route name which is selected. */
The documentation should be updated as well.

2024-12-30 11:48 UTC, illume commented on frontend/src/components/Sidebar/__snapshots__/Sidebaritem.SublistExpanded.stories.storyshot
> +                      class="MuiButtonBase-root MuiListItem-root MuiListItem-gutters MuiListItem-padding MuiListItem-button Mui-selected css-sayhe9-MuiButtonBase-root-MuiListItem-root"
Can you please explain why this test result changed? I don't see any mention of why, so I'm wondering if it's intentional or a bug?

2025-01-02 10:07 UTC, sniok commented on frontend/src/components/Sidebar/__snapshots__/Sidebaritem.SublistExpanded.stories.storyshot
> +                      class="MuiButtonBase-root MuiListItem-root MuiListItem-gutters MuiListItem-padding MuiListItem-button Mui-selected css-sayhe9-MuiButtonBase-root-MuiListItem-root"
I incorrectly updated the story for this case. It's fixed now

2025-01-07 04:14 UTC, illume commented on frontend/src/components/Sidebar/__snapshots__/Sidebaritem.SublistExpanded.stories.storyshot
> +                      class="MuiButtonBase-root MuiListItem-root MuiListItem-gutters MuiListItem-padding MuiListItem-button Mui-selected css-sayhe9-MuiButtonBase-root-MuiListItem-root"
thanks!

2025-01-07 05:11 UTC, illume commented
I added a how to test section to the PR description.

2025-01-07 05:11 UTC, illume approved these changes
👍 thanks! Nice improvement.

2025-01-07 05:12 UTC, merged