frontend: Add Pod list metrics
headlamp-k8s/headlamp pull request #2653
Opened 2024-12-10 15:33 UTC by sniok

Fixes #1

2025-01-28 16:10 UTC, skoeva approved these changes
Tested and works, thanks for this

2025-01-29 14:05 UTC, joaquimrocha requested changes
Code looks fine but it's not accounting for when the metrics server is not installed. We do adapt the cluster overview's charts when there's no metrics-server, so here we should do something similar.

2025-02-10 11:23 UTC, illume commented
@sniok this has some conflicts with main branch now.

2025-02-10 11:30 UTC, illume commented
Tested it without rebasing to main...

- Does not fail without metrics server enabled (`minikube addons enable metrics-server`)
- Works with metrics server enabled. (`minikube addons disable metrics-server`) No cpu/mem columns.


![image](https://github.com/user-attachments/assets/97a908a0-4001-4548-ae75-5393ad1cb8ab)

2025-02-10 11:31 UTC, illume requested changes
Please fix conflicts with main.

2025-02-14 12:03 UTC, sniok commented
> Note there are some gaps in the table?
> 

Fixed an edge case when usage is exactly 0, it will now display 0.

![image](https://github.com/user-attachments/assets/70cfbdce-7d02-44e5-9b0f-f9a4d565fcab)

 For pods that don't have metrics (like a completed pod) it'll stay empty

![image](https://github.com/user-attachments/assets/fa853857-75b7-46f4-954f-eeb2828c5dba)

2025-02-14 13:36 UTC, joaquimrocha approved these changes

2025-02-14 13:40 UTC, merged